### ISSUE TITLE
Can I get just vertical section plot png instead with axis ?

### ISSUE THREAD

**Issue by Siddeshi** [Reading-eScience-Centre/edal-java#105]
Hi there,

I need vertical section png file without chart (without axis) to render it directly as an image. Can you please help me how can I achieve in **thredds** as it is generating chart for me?

This is the url i'm trying in my local:

**`http://localhost:8080/thredds/wms/testAll/ModelTemperature.nc?REQUEST=GetVerticalSection&LAYER=TEMP&CRS=CRS:84&ELEVATION=-145&TIME=2009-12-29T12:00:00.0000Z&LINESTRING=65.06689453125%2014.340454101563,75.20556640625%200.6182861328125&FORMAT=image/png&COLORSCALERANGE=-50,50&NUMCOLORBANDS=20&VERSION=1.1.1&PALETTE=ferret&LOGSCALE=false`**

Attaching the image file which is getting generate.

![potential temperature](https://user-images.githubusercontent.com/10955336/35523776-9fbadbae-0545-11e8-9327-c25a58f93858.png)

But image which I want is as below.

![render](https://user-images.githubusercontent.com/10955336/35523883-e51be530-0545-11e8-90d3-8fef61611fd2.png)

**Comment by guygriffiths** [comment]
Hi, thanks for getting in touch.  Unfortunately what you want want to do is not currently possible in THREDDS.  The charting methods of THREDDS are really designed for people who want a full chart, rather than a view onto the data.

I think that your best option would be to grab a subset of the data via the data access methods of THREDDS, that way you can plot the chart in whichever package you're most comfortable with.
