### ISSUE TITLE
How to customize Godiva3?

### ISSUE THREAD

**Issue by cehbrecht** [Reading-eScience-Centre/edal-java#61]
The Godiva3 has more features than i would need as a simple WMS viewer for my netcdf files. But it looks very "technical".

Is it possible to customize Godiva3? For example the map size ...

Is it possible to separate the Godiva3 from the wms service? So, the Godiva3 would be part of my web frontend but it uses ncWMS pure wms service on another host.

It is hard to navigate with the current "time slider". Leaflet has an easier to use timedimension plugin:

http://apps.socib.es/Leaflet.TimeDimension/examples/example5.html

**Comment by guygriffiths** [comment]
There is very limited possibility to configure Godiva3.  On load, it queries the URL "getconfig" on the server.  If this returns a JSON object with values for "mapHeight" and "mapWidth" then they will be used.  Otherwise it is only possible to customise Godiva3 by modifying the source and rebuilding it.

You can separate Godiva3 from the WMS by specifying the "server" URL parameter.  For example, on my local installation, I can visit the URL:
http://localhost:8080/ncWMS2/Godiva3.html?server=http://godiva.rdg.ac.uk/ncWMS2/wms
and see all of the datasets available on our demo server.  However, I'm not sure what you mean by "ncWMS pure wms" - ncWMS has some extensions to WMS, so if it's ncWMS it's almost by definition NOT "pure wms".  Godiva3 only supports ncWMS servers - standard WMS servers do not have the functionality required for Godiva3 to use them (but ncWMS servers will work with standard WMS clients).

If you click the label for the time control (i.e. the word "Time), then the control will change between a calendar and a drop-down list of available times.  Currently there are no plans to implement a time slider control.

**Comment by cehbrecht** [comment]
> However, I'm not sure what you mean by "ncWMS pure wms" 

yes, i meant using a remote ncWMS with godiva3. So, separating client and server.

> If you click the label for the time control (i.e. the word "Time), then the control will change between a calendar and a drop-down list of available times.

good to know :)
