### ISSUE TITLE
"Feature Info Unavailable" for non-time-dependent variables

### ISSUE THREAD

**Issue by rsignell-usgs** [Reading-eScience-Centre/edal-java#80]
On my ncWMS2 endpoint (http://gamone.whoi.edu/ncWMS/Godiva3.html), when I click on a variable that does not depend on time, like the water depth (e.g. "COAWST" => "h") , I get back "Feature Info Unavailable":
![2017-01-19_17-04-04](https://cloud.githubusercontent.com/assets/1872600/22127735/459c3318-de6b-11e6-944e-00fb3eb121e2.png)

This is happening with all the non-time-dependent variables for both regular CF (e.g. COAWST) and unstructured UGRID (e.g. FVCOM_BOSTON) models.

**Comment by guygriffiths** [comment]
@rsignell-usgs Seems to be caused by failure to parse when there is an empty <time> tag in the FeatureInfo response.  Not sure why it was responding with an empty tag, rather than just omitting it, but I've fixed the Godiva issue and put a check in to try and stop it returning empty in the first place.  It'll be in the next release.

**Comment by rsignell-usgs** [comment]
@guygriffiths , awesome!    Thanks!
