### ISSUE TITLE
Support for raw NCML FMRC

### ISSUE THREAD

**Issue by acrosby** [Reading-eScience-Centre/edal-java#93]
Does edal support raw ncml fmrcs or is it expected that people will be using TDS to do this? I have an fmrc aggregation that seems to be valid in Tools-ui, and ncwms2 reads the ncml with no errors, but the dataset appears to be time-disabled. I am only interested in the "best" series.

**Comment by guygriffiths** [comment]
No, currently there's no support for NcML FMRCs.  I looked into it a long time ago, so the details are hazy, but I seem to recall that I was trying to use an NcML representation of an FMRC to perform automatic timeseries aggregation on files with overlapping time axes (again, only looking for the "best" time series).  I remember that it didn't work, but I don't remember why not.
Although by no means the most likely option, it's possible that the issue was with the NetCDF-Java libraries  and we've updated to a 5.x release of those recently, so things may have changed.  If you can attach the NcML, I'll take a look and see if it can be made to work.

**Comment by acrosby** [comment]
Hi @guygriffiths, here is the NCML that I am using. The data is proprietary, do you mind if i send some files to you separately? 

```
<?xml version="1.0" encoding="UTF-8"?>                                     
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2" enhance="true" >
     <aggregation dimName="run" type="forecastModelRunCollection" >          
       <scan location="/media/GLB15MIN/" suffix=".nc" enhance="true" />       
    </aggregation>                                                         
</netcdf> 
```

**Comment by guygriffiths** [comment]
@acrosby - Thanks for that.  I'm happy for you to send me some files separately.  If they're small enough to email (bearing in mind that just 2 or 3 files would be sufficient), I'm on guy.griffiths@the-iea.org, otherwise let me know how you want to go about it.

**Comment by acrosby** [comment]
@guygriffiths is this now taken care of in the releases of edal and ncwms?

https://github.com/Reading-eScience-Centre/edal-java/commit/73fccd85ea8f9ba05f5f1d97b79947c6647132b0

Thanks,
Alex

**Comment by guygriffiths** [comment]
@acrosby - Yes, it should be.  I'll close the issue, but feel free to reopen it if it doesn't work for you (if you can?  If not, just ping me an email)
